---
- name: Download Helm command line tool
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    return_content: true
  register: helm_installer

- name: Install Helm
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ helm_installer.content }}"
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"

- name: Install pip3 and git
  package:
    name:
      - python3-pip
      - git
      - python3-kubernetes
    state: latest

#python new installation in new versions of python: 
#pip install kubernetes
# error: externally-managed-environment
# × This environment is externally managed
# ╰─> To install Python packages system-wide, try apt install
#     python3-xyz, where xyz is the package you are trying to
#     install.


# - name: Install pre-requisites pip packages
#   pip:
#     name:
#       - pyyaml
#       - kubernetes 
#     executable: pip3
